// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: podservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建设备请求（增加 namespace 字段）
type CreatePodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"` // 测试固定传 test
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodRequest) Reset() {
	*x = CreatePodRequest{}
	mi := &file_podservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodRequest) ProtoMessage() {}

func (x *CreatePodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodRequest.ProtoReflect.Descriptor instead.
func (*CreatePodRequest) Descriptor() ([]byte, []int) {
	return file_podservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePodRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *CreatePodRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreatePodRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type CreatePodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePodReply) Reset() {
	*x = CreatePodReply{}
	mi := &file_podservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePodReply) ProtoMessage() {}

func (x *CreatePodReply) ProtoReflect() protoreflect.Message {
	mi := &file_podservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePodReply.ProtoReflect.Descriptor instead.
func (*CreatePodReply) Descriptor() ([]byte, []int) {
	return file_podservice_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePodReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePodReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeletePodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePodRequest) Reset() {
	*x = DeletePodRequest{}
	mi := &file_podservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodRequest) ProtoMessage() {}

func (x *DeletePodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_podservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodRequest.ProtoReflect.Descriptor instead.
func (*DeletePodRequest) Descriptor() ([]byte, []int) {
	return file_podservice_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePodRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *DeletePodRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DeletePodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePodReply) Reset() {
	*x = DeletePodReply{}
	mi := &file_podservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePodReply) ProtoMessage() {}

func (x *DeletePodReply) ProtoReflect() protoreflect.Message {
	mi := &file_podservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePodReply.ProtoReflect.Descriptor instead.
func (*DeletePodReply) Descriptor() ([]byte, []int) {
	return file_podservice_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePodReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeletePodReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_podservice_proto protoreflect.FileDescriptor

const file_podservice_proto_rawDesc = "" +
	"\n" +
	"\x10podservice.proto\"a\n" +
	"\x10CreatePodRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\"D\n" +
	"\x0eCreatePodReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x10DeletePodRequest\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"D\n" +
	"\x0eDeletePodReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2n\n" +
	"\n" +
	"PodManager\x12/\n" +
	"\tCreatePod\x12\x11.CreatePodRequest\x1a\x0f.CreatePodReply\x12/\n" +
	"\tDeletePod\x12\x11.DeletePodRequest\x1a\x0f.DeletePodReplyB\tZ\a./pb;pbb\x06proto3"

var (
	file_podservice_proto_rawDescOnce sync.Once
	file_podservice_proto_rawDescData []byte
)

func file_podservice_proto_rawDescGZIP() []byte {
	file_podservice_proto_rawDescOnce.Do(func() {
		file_podservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_podservice_proto_rawDesc), len(file_podservice_proto_rawDesc)))
	})
	return file_podservice_proto_rawDescData
}

var file_podservice_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_podservice_proto_goTypes = []any{
	(*CreatePodRequest)(nil), // 0: CreatePodRequest
	(*CreatePodReply)(nil),   // 1: CreatePodReply
	(*DeletePodRequest)(nil), // 2: DeletePodRequest
	(*DeletePodReply)(nil),   // 3: DeletePodReply
}
var file_podservice_proto_depIdxs = []int32{
	0, // 0: PodManager.CreatePod:input_type -> CreatePodRequest
	2, // 1: PodManager.DeletePod:input_type -> DeletePodRequest
	1, // 2: PodManager.CreatePod:output_type -> CreatePodReply
	3, // 3: PodManager.DeletePod:output_type -> DeletePodReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_podservice_proto_init() }
func file_podservice_proto_init() {
	if File_podservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_podservice_proto_rawDesc), len(file_podservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_podservice_proto_goTypes,
		DependencyIndexes: file_podservice_proto_depIdxs,
		MessageInfos:      file_podservice_proto_msgTypes,
	}.Build()
	File_podservice_proto = out.File
	file_podservice_proto_goTypes = nil
	file_podservice_proto_depIdxs = nil
}
