// Code generated by trpc-go/trpc-cmdline. DO NOT EDIT.
// source: podservice.proto

package pb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// PodManagerService defines service.
type PodManagerService interface {
	CreateDeployment(ctx context.Context, req *CreateDeploymentRequest) (*CreateDeploymentReply, error)
	DeleteDeployment(ctx context.Context, req *DeleteDeploymentRequest) (*DeleteDeploymentReply, error)
	CreatePod(ctx context.Context, req *CreatePodRequest) (*CreatePodReply, error)
	DeletePod(ctx context.Context, req *DeletePodRequest) (*DeletePodReply, error)
	GetPod(ctx context.Context, req *GetPodRequest) (*GetPodReply, error)
	CreateService(ctx context.Context, req *CreateServiceRequest) (*CreateServiceReply, error)
	DeleteService(ctx context.Context, req *DeleteServiceRequest) (*DeleteServiceReply, error)
	GetService(ctx context.Context, req *GetServiceRequest) (*GetServiceReply, error)
}

func PodManagerService_CreateDeployment_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateDeploymentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).CreateDeployment(ctx, reqbody.(*CreateDeploymentRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PodManagerService_DeleteDeployment_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteDeploymentRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).DeleteDeployment(ctx, reqbody.(*DeleteDeploymentRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PodManagerService_CreatePod_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreatePodRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).CreatePod(ctx, reqbody.(*CreatePodRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PodManagerService_DeletePod_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeletePodRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).DeletePod(ctx, reqbody.(*DeletePodRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PodManagerService_GetPod_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetPodRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).GetPod(ctx, reqbody.(*GetPodRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PodManagerService_CreateService_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &CreateServiceRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).CreateService(ctx, reqbody.(*CreateServiceRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PodManagerService_DeleteService_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &DeleteServiceRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).DeleteService(ctx, reqbody.(*DeleteServiceRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func PodManagerService_GetService_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &GetServiceRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PodManagerService).GetService(ctx, reqbody.(*GetServiceRequest))
	}
	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// PodManagerServer_ServiceDesc descriptor for server.RegisterService.
var PodManagerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.go-rpc.podmanager.PodManager",
	HandlerType: ((*PodManagerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/CreateDeployment",
			Func: PodManagerService_CreateDeployment_Handler,
		},
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/DeleteDeployment",
			Func: PodManagerService_DeleteDeployment_Handler,
		},
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/CreatePod",
			Func: PodManagerService_CreatePod_Handler,
		},
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/DeletePod",
			Func: PodManagerService_DeletePod_Handler,
		},
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/GetPod",
			Func: PodManagerService_GetPod_Handler,
		},
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/CreateService",
			Func: PodManagerService_CreateService_Handler,
		},
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/DeleteService",
			Func: PodManagerService_DeleteService_Handler,
		},
		{
			Name: "/trpc.go-rpc.podmanager.PodManager/GetService",
			Func: PodManagerService_GetService_Handler,
		},
	},
}

// RegisterPodManagerService registers service.
func RegisterPodManagerService(s server.Service, svr PodManagerService) {
	if err := s.Register(&PodManagerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("PodManager register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedPodManager struct{}

func (s *UnimplementedPodManager) CreateDeployment(ctx context.Context, req *CreateDeploymentRequest) (*CreateDeploymentReply, error) {
	return nil, errors.New("rpc CreateDeployment of service PodManager is not implemented")
}
func (s *UnimplementedPodManager) DeleteDeployment(ctx context.Context, req *DeleteDeploymentRequest) (*DeleteDeploymentReply, error) {
	return nil, errors.New("rpc DeleteDeployment of service PodManager is not implemented")
}
func (s *UnimplementedPodManager) CreatePod(ctx context.Context, req *CreatePodRequest) (*CreatePodReply, error) {
	return nil, errors.New("rpc CreatePod of service PodManager is not implemented")
}
func (s *UnimplementedPodManager) DeletePod(ctx context.Context, req *DeletePodRequest) (*DeletePodReply, error) {
	return nil, errors.New("rpc DeletePod of service PodManager is not implemented")
}
func (s *UnimplementedPodManager) GetPod(ctx context.Context, req *GetPodRequest) (*GetPodReply, error) {
	return nil, errors.New("rpc GetPod of service PodManager is not implemented")
}
func (s *UnimplementedPodManager) CreateService(ctx context.Context, req *CreateServiceRequest) (*CreateServiceReply, error) {
	return nil, errors.New("rpc CreateService of service PodManager is not implemented")
}
func (s *UnimplementedPodManager) DeleteService(ctx context.Context, req *DeleteServiceRequest) (*DeleteServiceReply, error) {
	return nil, errors.New("rpc DeleteService of service PodManager is not implemented")
}
func (s *UnimplementedPodManager) GetService(ctx context.Context, req *GetServiceRequest) (*GetServiceReply, error) {
	return nil, errors.New("rpc GetService of service PodManager is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// PodManagerClientProxy defines service client proxy
type PodManagerClientProxy interface {
	CreateDeployment(ctx context.Context, req *CreateDeploymentRequest, opts ...client.Option) (rsp *CreateDeploymentReply, err error)
	DeleteDeployment(ctx context.Context, req *DeleteDeploymentRequest, opts ...client.Option) (rsp *DeleteDeploymentReply, err error)
	CreatePod(ctx context.Context, req *CreatePodRequest, opts ...client.Option) (rsp *CreatePodReply, err error)
	DeletePod(ctx context.Context, req *DeletePodRequest, opts ...client.Option) (rsp *DeletePodReply, err error)
	GetPod(ctx context.Context, req *GetPodRequest, opts ...client.Option) (rsp *GetPodReply, err error)
	CreateService(ctx context.Context, req *CreateServiceRequest, opts ...client.Option) (rsp *CreateServiceReply, err error)
	DeleteService(ctx context.Context, req *DeleteServiceRequest, opts ...client.Option) (rsp *DeleteServiceReply, err error)
	GetService(ctx context.Context, req *GetServiceRequest, opts ...client.Option) (rsp *GetServiceReply, err error)
}

type PodManagerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewPodManagerClientProxy = func(opts ...client.Option) PodManagerClientProxy {
	return &PodManagerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *PodManagerClientProxyImpl) CreateDeployment(ctx context.Context, req *CreateDeploymentRequest, opts ...client.Option) (*CreateDeploymentReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/CreateDeployment")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("CreateDeployment")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateDeploymentReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PodManagerClientProxyImpl) DeleteDeployment(ctx context.Context, req *DeleteDeploymentRequest, opts ...client.Option) (*DeleteDeploymentReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/DeleteDeployment")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("DeleteDeployment")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteDeploymentReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PodManagerClientProxyImpl) CreatePod(ctx context.Context, req *CreatePodRequest, opts ...client.Option) (*CreatePodReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/CreatePod")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("CreatePod")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreatePodReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PodManagerClientProxyImpl) DeletePod(ctx context.Context, req *DeletePodRequest, opts ...client.Option) (*DeletePodReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/DeletePod")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("DeletePod")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeletePodReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PodManagerClientProxyImpl) GetPod(ctx context.Context, req *GetPodRequest, opts ...client.Option) (*GetPodReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/GetPod")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("GetPod")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetPodReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PodManagerClientProxyImpl) CreateService(ctx context.Context, req *CreateServiceRequest, opts ...client.Option) (*CreateServiceReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/CreateService")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("CreateService")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &CreateServiceReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PodManagerClientProxyImpl) DeleteService(ctx context.Context, req *DeleteServiceRequest, opts ...client.Option) (*DeleteServiceReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/DeleteService")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("DeleteService")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &DeleteServiceReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *PodManagerClientProxyImpl) GetService(ctx context.Context, req *GetServiceRequest, opts ...client.Option) (*GetServiceReply, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.go-rpc.podmanager.PodManager/GetService")
	msg.WithCalleeServiceName(PodManagerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("PodManager")
	msg.WithCalleeMethod("GetService")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &GetServiceReply{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
